/**
 * Do NOT edit this file!
 *
 * The function mimics the <script> tag, but with error handling. It will catch errors and convert 
 * into an error message on the web page. The purpose is to be able to work on different parts of
 * the web page in parallel without causing your errors to block progress for others.
 *
 * @param  name Javascript to be loaded in corresponding folder, i.e. corresponds to <script src="name/name.js"></script>
 */
function createScript(name) {
    const src = `${name}/${name}.js`;
    var script = document.createElement('script');
    script.src = src;
    script.onload = function onload() {
        const fn = window[name]
        const el = document.querySelector(`#${name}`);
        if (typeof fn !== 'function') {
            el.innerHTML = `Something broken in ${name}. It is ${typeof fn}`;
        } else {
            try {
                el.innerHTML = fn(news);
            } catch (e) {
                el.innerHTML = `<pre><code>${e.stack}</code></pre>`;
            }
        }
    }
    document.body.append(script);
    return script;
}

/**
 * Load header, article and list respectively.
 */
createScript('header');
createScript('article');
createScript('list');
